registry:
  url: 'https://github.com/{name}/{repository}/releases/download/{version}'
  name: ''
  repository: ''
  version: 'latest'
logging:
  level: 'DEBUG'
plugins:
  - speech-interface-plugin
  - text-interface-plugin